.PHONY: build run clean ir test

build:
	./autojar.sh

clean:
	./clean.sh

run:
	python3 ./walk.py

ir:
	./irc.sh

mips:
	./mips.sh

casetest:
	python3 ./testcase.py

mipsself:
	sh ./mips_self.sh

llvmself:
	sh ./llvm_self.sh

